require_relative '../lib/decorators'
require_relative '../lib/save_decorators'
require_relative '../lib/rentals'
require_relative '../lib/classroom'
require_relative '../lib/student'
require_relative '../lib/teacher'
require_relative '../lib/person'
require_relative '../lib/book'

require 'json'